module.exports = [
    {
        name: "Crystals for Beginners: 7 must have stones",
        description: "There are crystals for clearing chakras, crystals for protective measures, crystals for self-care, crystals for emotional energy, and crystals for attracting all that you desire and more. You just have to choose one that works with your own systems of power. You may be wondering how you would even know which crystal was the right one for you, but this is where we take out very first lesson in working with crystals. It is all about learning to trust yourself and letting your intuition guide you. If we learn to tap into that well of wisdom, we know exactly what we need for our own self-care and we know where in our wellness journey we are rising and where we may be falling. Taking this knowledge and finding crystals that can help strengthen our strengths and build resilience in places we may have fragility is a glorious act of self-care just in itself. As mentioned, the best way to pick crystals that work for you is to use your intuition and see what draws you in. Sometimes, your eye will automatically rove towards a certain shape or color of crystal, other times your curiosity is sparked by the name or something within connects when you hear about the healing properties, a tiny whisper inside that says yes. We understand that with so many crystals out there it can be overwhelming to choose one which is where this beginners guide to the most popular crystals comes in handy. We have chosen a selection of first crystals that are easy to get hold of, gentle to work with, and can be a great way of getting your healing stones collection up and running. Here are some of the best crystals for beginners: 1. Clear Quarts, 2. Amethyst, 3. Rose Quarts, 4. Moonstone, 5. Laapis Lazuli 6. Pyrite and 7. Citrine.",
        img: "https://www.sunset.com/wp-content/uploads/48539da9a510de488f467ac215cd3191-750x0-c-default.jpg",
    },
    {
        name: "Crystals For Sleep: 9 Stones To Get You Into REM",
        description: "The thing is sleep is not something we can skip out on. It is a vital time for our body to rest and for our cells to heal and rejuvenate. Our quality of sleep affects everything from how we consume food to how we process information and make decisions. Good sleep helps us to be productive, it boosts our metabolism, and it helps our immune system to stand up the challenge and thrive. It is not something we can risk depriving ourselves off. Healing crystals can help us to find that place of rich and rewarding slumber. Some of our favorite crystals help to soothe anxieties and clear the mind, granting us that mental space we need to let go of our worries and to find that mental space of rest. By placing one of these glimmering rocks beneath your pillow or on your person, you could clear out negative energy and finally get the solid sleep you need. One of the best things about crystals is the fact that no two are alike. Crystals come with a delightful dose of their own healing energy. They can arouse that zest for life, they can align different chakras, they can fill your heart with love, provide a protective cloak against bad energy, and they can also soothe the mind and help you sleep. We are bound to find getting a good nights sleep much easier if we have an abundance of positive energy surrounding us or if we feel confident that the worries plaguing our mind can be solved. We have selected the best stones for soothing the mind and the body, bringing to light physical rest, and building a sense of rising wellbeing so you can get the shuteye you need. Here are some of the best crystals for better sleep: 1. Selenite, 2. Celesite, 3. Lepidolite, 4. Howlite, 5. Amethyst, 6. Angelite, 7.Smoky Quarts, 8. Rose Quarts, and 9. Black Tourmaline.",
        img: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F34%2F2022%2F02%2F22%2Fsleeping-dog-in-bed-getty-alt-0222-2000.jpg&q=60',
    },
    {
        name: 'How Healing Crystals Work',
        description: 'While there is no scientific evidence that crystals work to physically heal, there are a ton of ancient history and modern-day anecdotes that showcase the positive presence that crystals bring into our life across the three plains of the body, mind, and soul. From reiki to vision quests, meditation, and mapping, crystals are ever ready to bring their healing power to the table as they are amazing at tapping into energy fields. While crystals have their own special energies and their own frequency of vibrations, they are also amazing conduits for harnessing the healing energy of the universe. They are able to transmute the flow of energy to the body, which helps to unblock the chakras, send energy where it is needed, and balance out your inner world.',
        img: 'https://emilycottontop.com/wp-content/uploads/2022/02/image_d3a8d2e7-03ee-4b9e-a14b-210761563be3_grande.jpg',
    }
]